### ISSUE TITLE
Great game!

### ISSUE THREAD

**Issue by ronghuang0** [jeantimex/five-in-a-row#1]
I saw this on the list of sites using react and I really like it. Is there a deployed version that I can play with my friends haha? Thanks.

**Comment by jeantimex** [comment]
Thanks mate! I am tying to host it on Digital Ocean, the thing is, this game doesn't allow players to create rooms, I am thinking how to optimize that, but will keep you updated.

Or you can download the repo and deploy on your node server. :)
